//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCEW.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolesMaster()
        {
            this.RolesAndRightsMasters = new HashSet<RolesAndRightsMaster>();
        }
    
        public long RoleId { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesAndRightsMaster> RolesAndRightsMasters { get; set; }
    }
}
