//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCEW.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesAndRightsMaster
    {
        public long RightsId { get; set; }
        public Nullable<long> RoleId { get; set; }
        public Nullable<long> ActionId { get; set; }
        public Nullable<long> PageId { get; set; }
        public Nullable<bool> IsRight { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual RolesMaster RolesMaster { get; set; }
    }
}
