//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCEW.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleActionMaster
    {
        public long ActionId { get; set; }
        public string ActionName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
